import Head from "next/head";

const HeaderStyle = {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "50vh",
    fontSize: "4rem",
};

const LinkStyle = {
    textDecoration: "underline",
};

const HeaderLink = {
    ...HeaderStyle,
    ...LinkStyle,
};

function HelloWorld() {
    return (
        <a href={"https://www.cornelldti.org/"} style={HeaderLink}>
            Hello World
        </a>
    );
}

export default function Home() {
    return (
        <div>
            <Head>
                <title>Basic Inline CSS Template</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <HelloWorld />
            </main>
        </div>
    );
}
